### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by soetakara** [soetakara/protospace-36189#1]
#URL
https://protospace-36189.herokuapp.com/

**Comment by snkw-works** [comment]
@soetakara さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **正しく編集できた場合は、詳細ページへ遷移するよう修正しましょう**
編集完了後にトップページに遷移してしまいます。

- [x] **コメントを投稿すると、投稿したコメントとその投稿者名が、対象プロトタイプの詳細ページにのみ表示されるよう修正しましょう**
コメントの投稿者名ではなく、プロトタイプの投稿者名が表示されてしまいます。


- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するよう修正しましょう**
プロトタイプ詳細ページの投稿者名をクリックすると、ユーザー詳細ページではなくトップページに遷移してしまいます。
<img width="801" alt="スクリーンショット_2021-10-23_10_44_13" src="https://user-images.githubusercontent.com/54050089/138537871-603a2e3a-e5fa-4b0c-800c-8e239d8694ac.png">



修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by soetakara** [comment]
上記内容修正しました。確認の程、宜しくおねがいします。

**Comment by snkw-works** [comment]
@soetakara さん、修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
